### PR TITLE
Added `glmer` function 

### PR DESCRIPTION
**Pull request by jvparidon**
Added `glmer` function as mentioned in #5. In order to preserve `lme4::glmer`'s functionality, I ended up copying most of that code base and integrating with Ben Bolker's multimembership random effects code.
Appears functional, returns `glmerModMultiMember` object (added unit test for checking valid return type). Needs more validation & more rigorous unit tests.

### CODE REVIEW

**Comment by palday** [comment]
I need to take some time to think about this (maybe taking another look at the LMM code), but I suspect that it might almost be easier to call glmer but without actually fitting the model (IIRC there's a way to do this, but it's been a while), reach into the returned object and modify it appropriately. That would avoid a lot of the code duplication (and associated license issues) going on here.

**Comment by jvparidon** [comment]
The problem is that the point where we call `lme4::glFormula` and insert our fake factors and multiple membership weight matrices is located just _before_ calling `lme4::mkGlmerDevfun` (and returning the deviance function before fitting the model, if `devFunOnly` is true).

So if we do what you suggest, we'd end up calling `lme4::glmer` to create the deviance function, then going back and calling `lme4::glFormula` with the fake factors and weight matrices, then calling calling `lme4::mkGlmerDevfun` to _recreate_ the deviance function with multiple membership, and then having to still call `lme4::optimizeGlmer`, `lme4::checkConv`, and `lme4::mkMerMod` (etc.)

It ends up using a lot of `lme4` code verbatim anyway, and you do the deviance function stuff twice. I'm not sure that's an improvement over the current situation.

**Comment by jvparidon** [comment]
I'll rewrite `glmer` cf. #13, shouldn't be too hard.

**Comment by jvparidon** [comment]
Superseded by #15.

**Pull request closed without merging**
